### ISSUE TITLE
How to do graceful shutdown of server?

### ISSUE THREAD

**Issue by MichaelHipp** [mholt/certmagic#10]
## What is your question?

As of Go 1.8, the http server from the std lib has a Shutdown() method to gracefully stop the server. Is there anything similar for the certmagic server?

## What have you already tried?

Looking in the godoc's for any .Stop() or .Shutdown() methods.

## Include any other information or discussion.

Here's an article that shows how this is done with the http server from Go: [https://hackernoon.com/how-to-safely-shut-down-a-server-in-go-aec16dfbc57f](url)

## Bonus: What do you use this package for, and does it help you?

Building a production website that hopefully will use this to keep its certs current.

**Comment by mholt** [comment]
There are several ways you could do this, but this is the simplest, if you don't mind not using the HTTP challenge (and relying solely on TLS-ALPN):

```go
magicLn, err := certmagic.Listen([]string{"example.com"})
if err != nil {
	return err
}
srv := http.Server{
	// configure your server here
}

go srv.Serve(magicLn)

time.Sleep(10 * time.Second)

srv.Shutdown(context.Background())
```

(Of course, this is a contrived example)

If you want both challenge types you can make a `magic := certmagic.NewDefault()` and then use that to get a TLS config and HTTP handler like the README examples show.
