### ISSUE TITLE
List of known storage implementations

### ISSUE THREAD

**Issue by aidansteele** [mholt/certmagic#11]
Hi,

Do you plan on maintaining a list of known `Storage` implementations? While I could empathise with you potentially not wanting to maintain a plethora of community-contributed implementations, it might be helpful to maintain a list of known implementations out in the wild, to dedupe effort and get people up and running faster.

My own selfish desire for this is borne out of hoping that someone else has already implemented an AWS DynamoDB implementation -- but it's a bit hard to find anything on Google. 

(Btw, *Fantastic* project - love your work)

**Comment by mholt** [comment]
Yes! In fact, I want to start the wiki on this project. We should put the list there, perhaps.

**Comment by mholt** [comment]
Wish granted: https://github.com/mholt/certmagic/wiki/Storage-Implementations

I opened the wiki for anyone to edit.
