### ISSUE TITLE
Disable certificate renewal

### ISSUE THREAD

**Issue by paolobarbolini** [mholt/certmagic#21]
## What would you like to have changed?
Ability to disable certificate renewal.

## Why is this feature a useful, necessary, and/or important addition to this project?
I'm using the dns challenge since I need wildcard certificates, the problem is that every server needs to know the credentials for my dns provider, which I find unnecessary since I could have a single server do the renewal, or something hosted on some serverless platform, so because of this it would be awesome to have the ability to disable renewal on the rest of the servers.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
I'm setting up a dns provider but passing in invalid credentials, which will probably become a problem when certmagic will decide it's time to renew the certificates.

**Comment by mholt** [comment]
I had never thought about this before, but I guess it makes sense. You'd just be putting a lot of trust on the external certificate renewal process to do its job. But CertMagic already will check on disk at renewal time before attempting a renewal, so replacing the certificate on disk (_along with its metadata in the lego-compatible format!_) should work, no matter how that gets done.

We'd just need a config setting (boolean probably) to disable renewals.

**Comment by paolobarbolini** [comment]
Yeah, now that I'm looking at it we could allow the config `RenewDurationBefore` to be set to a negative value to disable renewal.

I'll send a PR later if this sounds good.

**Comment by mholt** [comment]
Closing this for now. Thinking on it more, I don't think disabling renewal is a good way to solve this problem, which is more about credentials management.
