### ISSUE TITLE
Non SNI Certificates

### ISSUE THREAD

**Issue by 256dpi** [mholt/certmagic#22]
Commit c1d472b46046ee329c099086d689ada0c44d56b0 made certmagic set the listeners IP address as the certificate name in case the server name has not been provided (not using SNI).

In a current case I have an app with certmagic running in docker. If a non SNI client is connecting, certmagic sets the private `172.17.X` ip address of the docker container as the certificate name and since there is no certificate managed under that name it logs the error "no certificate available for 172.17.X".

Can we add a switch to the configuration to set a fallback certificate name for such cases? In my case I run certmagic with a single domain and would like to use the same certificate also for non SNI clients.

Maybe something like:

```go
certmagic.NonSNIDomain = "example.com"
```

In case the option is not set, we can fallback to the current behaviour.

**Comment by mholt** [comment]
I'm glad you brought this up; it could definitely be a reasonable fix for https://github.com/mholt/caddy/issues/2438.

How about `DefaultServerName` instead? If left empty, it'll still try the IP address then, but if not, it can serve a certificate for DefaultServerName if it has one.

Sound good?

**Comment by 256dpi** [comment]
Sounds good, can I help out with a PR?

**Comment by mholt** [comment]
Sure! I'll review it today.

**Comment by mholt** [comment]
Hm, after looking at the required changes, we'll need a way for Caddy to choose a TLS config in the absence of SNI, so the `default_sni` option thingie I suggested above would not only set the DefaultServerName value here in CertMagic, it'd also have to make that TLS config the "default", probably by keying it in the `configGroup` by an additional string value of `""`. (The algorithm for choosing a config group and a certificate within a config is basically the same.)
