### ISSUE TITLE
add selfSignedCertificate

### ISSUE THREAD

**Issue by mschneider82** [mholt/certmagic#25]
## What would you like to have changed?
it would be usefull to have the "newSelfSignedCertificate" code migrated from caddy to certmagic.

## Why is this feature a useful, necessary, and/or important addition to this project?
In order to test applications in local docker env's.
requesting, creating, signing and managing a selfsigned for an application is still pain and needs some more magic!

I think a good solution would be to have something simular like certmagic.HTTPS() which creates and uses a selfsigned

**Comment by mschneider82** [comment]
another idea would be to use something simular to set `certmagic.CA := "self-singed`" and then create the selfsigned certificate. With this idea no extra function would be needed and the HTTPS() could handle it

**Comment by mholt** [comment]
I think the best way now, after the refactoring, is to make a Manager implementation that simply generates self-signed certs: https://godoc.org/github.com/mholt/certmagic#Manager

**Comment by 89z** [comment]
https://github.com/caddyserver/certmagic/issues/124
