### ISSUE TITLE
Export Cache instance as part of Config type

### ISSUE THREAD

**Issue by wI2L** [mholt/certmagic#32]
## What would you like to have changed?
I would like to expose the `Cache` instance that is part of the `Config` type.

## Why is this feature a useful, necessary, and/or important addition to this project?
The `Cache` instance has two methods `Stop` and `RenewManagedCertificates`. As part of a Graceful Shutdown, I would like to be able to close the cache renewal loop properly.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
I saw in the `caddy` sources that you register the call to `Close` with an event handler. However, in my current implementation, the creation of the cache instance is part of the creation of a new `Config` type and is out of scope of my main type `Server` that manage graceful shutdown.

**Comment by mholt** [comment]
If you're doing advanced things like graceful shutdown, I would just follow the advanced steps and make your own cache instead: https://github.com/mholt/certmagic#advanced-use
