### ISSUE TITLE
StorageAPI agnostic from datastore

### ISSUE THREAD

**Issue by dschwar** [mholt/certmagic#33]
## What would you like to have changed?
Currently the Storage interface makes many references to store items in a file system. Consider reducing the coupling to the file system.

| What | Why | Workaround |
| ----- | ----- | ------------ |
| In the Storage and Locker interfaces, the methods take key strings that are in the format of a filesystem path  | This could make it difficult for different storage implementations to look up certificates. In the past, the Storage interface used the host as the way to reference a certificate/private key, why the switch away from this? | parse out the host from the key |
| In the Storage interface, List takes in a prefix and recursive | Consider removing the recursive options since it exists only for keys that are in filesystems | hacks to make this work  outside of filesystems |
| In the Storage interface, the Stat method returns a KeyInfo which has Size and IsTerminal | these are hard to compute for non-filesystem storage mechanisms | these don't appear to be used anywhere, so can always return 0 and false. |

## Why is this feature a useful, necessary, and/or important addition to this project?
Allows for non-file based storage implementations (eg: MySQL).

**Comment by mholt** [comment]
These are good questions/requests, thanks for the issue @dschwar.

The Storage interface is designed to work well with _any_ key-value store, which includes a MySQL database and any other kind of database.

> In the Storage and Locker interfaces, the methods take key strings that are in the format of a filesystem path. This could make it difficult for different storage implementations to look up certificates. In the past, the Storage interface used the host as the way to reference a certificate/private key, why the switch away from this?

The Storage interface is now used for more than just certificates and keys. If we didn't encode a structure into object keys, we'd have to create methods for every new kind of object we wanted to access/query from storage.

> In the Storage interface, List takes in a prefix and recursive. Consider removing the recursive options since it exists only for keys that are in filesystems

Recursive is simply a traversal of the structure encoded in a key, it doesn't require traversing a file system. If there are keys "a/b/c" and "a/b/d" and we wanted to list "a" or "a/b", then it's simply a matter of returning the two keys, which in this case have that prefix (looking at whole parts of the "path" separated by `/`).

> In the Storage interface, the Stat method returns a KeyInfo which has Size and IsTerminal | these are hard to compute for non-filesystem storage mechanisms. these don't appear to be used anywhere, so can always return 0 and false.

Hm, you seem to be right, that these are not used anywhere, at least within CertMagic. Caddy doesn't appear to use them either. This is worth looking into.

> hacks to make this work outside of filesystems

Are there specific difficulties you are having? You refer to MySQL, but what's the actual problem?

**Comment by dschwar** [comment]
> The Storage interface is now used for more than just certificates and keys. If we didn't encode a structure into object keys, we'd have to create methods for every new kind of object we wanted to access/query from storage.

Have you considered making the types of objects stored in the datastore more concrete and then the implementation can decide how to store/retrieve the key based on the type desired? This would allow the implementor to decide whether to use prefixes or different tables.

> Recursive is simply a traversal of the structure encoded in a key, it doesn't require traversing a file system. If there are keys "a/b/c" and "a/b/d" and we wanted to list "a" or "a/b", then it's simply a matter of returning the two keys, which in this case have that prefix (looking at whole parts of the "path" separated by /).

I don't feel like this is trivial to implement in a database.

**Comment by mholt** [comment]
> Have you considered making the types of objects stored in the datastore more concrete and then the implementation can decide how to store/retrieve the key based on the type desired?

Yes, that is what Caddy used to do, and it was extremely difficult to work with.

I'm sorry if it appears difficult or confusing, but I don't think there's much we can helpfully do to simplify things at this point -- and there are already other implementations using the existing interface, and it works quite well, all it needs is some key-value store (and database tables can make good key-value stores).
