### ISSUE TITLE
Can't delete old OCSP staples: no such file or directory

### ISSUE THREAD

**Issue by evenh** [mholt/certmagic#4]
## What version of the package are you using?

9645f8e0e41c877ce99013b87602776a44bd1085

## What are you trying to do?

I'm trying to integrate CertMagic into my own project (see below for description).

## What steps did you take?

I constructed a new instance of CertMagic with a custom `Cache`, backed by a custom `FileStorage` storage. I did because I wanted to customize the folder which is used to store data fetched/generated by CertMagic.

(I can also see this behaviour when running "vanilla" as described in the readme, e.g. without specifying a custom cache or storage)

### Expected

I expected the stale OCSP staples routine to find the expected files in the filesystem.

### Observed

```
2018/12/12 20:42:17 [INFO] Scanning for stale OCSP staples
2018/12/12 20:42:17 [ERROR] While deleting old OCSP staples, unable to load staple file: open /Users/evenh/.intercert/server-data/foo.koderiet.org-812f94e6: no such file or directory
```

## How do you think this should be fixed?

By ensuring that the routine looks in the `ocsp` subfolder of the data directory (not in the root) used by the `Storage`.

## Please link to any related issues, pull requests, and/or discussion

N/A

## Bonus: What do you use CertMagic for, and do you find it useful?

I'm trying to create a little program that can run somewhere with an internet connection and requests DNS-validated certs on behalf of clients running in a locked down LAN.

**Comment by mholt** [comment]
Thank you for the report! I was able to reproduce similar errors... can you try the latest on master now? The way we handled List and Stat for keys was kind of clumsy; it's better now (although it necessitated one breaking change to the Storage interface, which should be OK, since we haven't tagged a release yet).

**Comment by evenh** [comment]
It happens every minute.

```
2018/12/12 23:32:34 [INFO] Listening on port 4300
2018/12/12 23:32:34 [INFO] Using directory /Users/evenh/.intercert/server-data for storage
2018/12/12 23:32:34 [INFO] Loaded whitelist: [koderiet.org evenh.net]
2018/12/12 23:32:34 [INFO] Certificate issuer service configured
2018/12/12 23:33:34 [INFO] Scanning for stale OCSP staples
2018/12/12 23:33:34 [INFO] Done checking OCSP staples
2018/12/12 23:33:34 [INFO] Scanning for stale OCSP staples
2018/12/12 23:33:34 [INFO] Done checking OCSP staples
2018/12/12 23:34:34 [INFO] Scanning for stale OCSP staples
2018/12/12 23:34:34 [INFO] Done checking OCSP staples
2018/12/12 23:34:34 [INFO] Scanning for stale OCSP staples
2018/12/12 23:34:34 [INFO] Done checking OCSP staples
2018/12/12 23:35:34 [INFO] Scanning for stale OCSP staples
2018/12/12 23:35:34 [INFO] Done checking OCSP staples
2018/12/12 23:35:34 [INFO] Scanning for stale OCSP staples
2018/12/12 23:35:34 [INFO] Done checking OCSP staples
```

I modified https://github.com/mholt/certmagic/blob/master/maintain.go#L306 in my `vendor` folder, just to verify the fix. I use MagicCert like this:

```go
// Construct the new certmagic instance
magic := certmagic.NewWithCache(IntercertCache(config), certmagic.Config{
	CA:                      config.Directory,
	Email:                   config.Email,
	Agreed:                  config.Agree,
	DisableHTTPChallenge:    true,
	DisableTLSALPNChallenge: true,
	KeyType:                 certcrypto.RSA4096,
	MustStaple:              false,
	DNSProvider:             dnsProvider,
})

// My code
issuer.client = magic
```

Nothing is customized, outside of using my own cache/storage as described in the issue description.

```go
func IntercertCache(config *config.ServerConfig) *certmagic.Cache {
	var storage = createStorage(config.Storage)
	log.Infof("Using directory %s for storage", config.Storage)

	return createCache(storage)
}

func createCache(storage certmagic.Storage) *certmagic.Cache {
	return certmagic.NewCache(storage)
}

func createStorage(dataDirectory string) certmagic.Storage {
	return certmagic.FileStorage{Path: dataDirectory}
}
```

**Comment by mholt** [comment]
Ah, it's probably because we have:

```go
var defaultCache = NewCache(DefaultStorage)
```

in the `cache.go` file. So, the default cache is performing maintenance, even if it is not used.

I've just pushed a commit that prints which cache is performing maintenance. That might help clear things up...

**Comment by mholt** [comment]
FYI: Setting the DNS challenge disables the other challenge types. (It's not bad that you're doing that, since you say that using the DNS challenge exclusively is part of the purpose of your project, and I can't guarantee that this will always be the case, but it surely makes sense IMO, ... anyway, just thought I'd point that out.)

**Comment by mholt** [comment]
Annnnd I just fixed another little bug related to the logic of the default certificate cache. Commit b408584 eliminates that initialization so you should not see extra log messages anymore.

**Comment by evenh** [comment]
Can confirm that these commits solve the behaviour that I was seeing. Thank you for being so responsive and quick to squash bugs :-)
