### ISSUE TITLE
QUIC support?

### ISSUE THREAD

**Issue by escholtz** [mholt/certmagic#42]
## What is your question?

Now that a whole 3 days have passed since merging QUIC support into Caddy (https://github.com/caddyserver/caddy/pull/2727), any plans to bring QUIC to certmagic? Would that even make sense or do the hooks already exist to use both?

## Bonus: What do you use this package for, and does it help you?

Simple and free TLS, it's amazing! Thanks for your generous work.

**Comment by mholt** [comment]
I don't think it really makes sense to do so until HTTP/3 becomes standardized. No browsers even use it yet.

Will revisit this in a year or so. We'll see how things go.

**Comment by paullj1** [comment]
Google Chrome, and Firefox added support since this closed. Still experimental, but I think we’re a lot closer than a year.

https://www.zdnet.com/article/cloudflare-google-chrome-and-firefox-add-http3-support/

**Comment by APoolio** [comment]
@mholt Is there any documentation that shows how to accomplish using CertMagic with our own HTTP/3 listener?
