### ISSUE TITLE
Error on install and compile.

### ISSUE THREAD

**Issue by lyihongl** [mholt/certmagic#44]
I did a go get of this package, and this error popped up. 

`# github.com/mholt/certmagic
../../mholt/certmagic/client.go:143:8: ht.ForceAttemptHTTP2 undefined (type *http.Transport has no field or method ForceAttemptHTTP2)`.

go version: 

`go version go1.10.4 linux/amd64`

Edit:

So after some digging around, in go/src/golang.org/x/net/http2/transport.go, `struct Transport` does *not* declare ForceAttemptHTTP2, but looking at https://github.com/golang/go/blob/master/src/net/http/transport.go, `struct Transport` does declare ForceAttemptHTTP2.

**Comment by DisposaBoy** [comment]
Go1.10 was released in Feb 2018; it's probably time to upgrade.
See also the Go release policy at https://golang.org/doc/devel/release.html#policy

**Comment by lyihongl** [comment]
Yea pretty dumb on my part lol.
