### ISSUE TITLE
Need help incorporating it in application

### ISSUE THREAD

**Issue by driftavalli** [mholt/certmagic#45]
## What is your question?

I have a type the following code but finding it hard to integrate certmagic
```
type Server struct {
  Port        int
  Addr        string
  HTTPServer  *http.Server
}

func (s *Server) Start(){
  s.HTTPServer.ListenAndServe()
}
```
I set values for `http.Server` later on with (`addr` and `handler`) so I can just call `http.ListenAndServe()`, however `certmagic.HTTPS()` seems to require two arguments. Am I able to call `certmagic` and use the default `addr`, `handler` etc?
## What have you already tried?

I tried just dropping `certmagic.HTTPS([]string{"example.com"})` but this throws an error. There doesn't seem to any other high level call to just drop in.

## Bonus: What do you use this package for, and does it help you?

Hoping to use it for an API

**Comment by mholt** [comment]
You need to pass in your http.Handler; whatever type of yours implements the http.Handler interface.
