### ISSUE TITLE
HTTP -> HTTPS redirect not working

### ISSUE THREAD

**Issue by lyihongl** [mholt/certmagic#46]
I currently have a domain name, lets just call `example.com`. When I open an incognito tab and enter just `example.com` I get the message `[ip of my droplet] returned invalid response.` However if I type `https://example.com` into the search bar, then my website loads.

I went into certmagic.go to and printed out the url that it was trying to redirect to, and its `https://[ip of my droplet]`.

 Is this a problem with my DNS setup?

Currently I have `example.com` to redirect to a masked ip, and that ip is `http://[server ip]:80`. I also have an A record pointing at my droplet ip.

Sorry if this a dumb question, I'm pretty new to web dev.

**Comment by mholt** [comment]
What does curl say? Use 'curl -v http://example.com' to get verbose output

**Comment by lyihongl** [comment]
* Rebuilt URL to: http://example.com/
*   Trying [ip]...
* TCP_NODELAY set
* Connected to example.com ([ip]) port 80 (#0)
> GET / HTTP/1.1
> Host: example.com
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 26 Sep 2019 03:39:52 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 874
< Connection: keep-alive
< X-Served-By: Namecheap URL Forward
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
    <head>
        <meta http-equiv='content-type' content='text/html; charset=UTF-8'>
        <meta name="KEYWORDS" content="">
        <meta name="DESCRIPTION" content="">
        <meta name="VERSION" content="">
        <link href="" rel="shortcut icon" type="image/x-icon">
        <title></title>
    </head>
    <frameset rows='100%, *' frameborder=no framespacing=0 border=0>
        <frame src="http://[droplet ip]" name=mainwindow frameborder=no framespacing=0 marginheight=0 marginwidth=0></frame>
    </frameset>
    <noframes>
        <h2>Your browser does not support frames. We recommend upgrading your browser.</h2><br><br>
        <center>Click <a href="http://[droplet ip]" >here</a> to enter the site.</center>
    </noframes>
</html>
* Connection #0 to host example.com left intact


One thing I want to point out, I've put my domain into ssl labs before, and it found 2 ips for it. Everywhere in the output where I have `[ip]` is not the ip of my droplet, but the ip of the other server .

**Comment by mholt** [comment]
Thanks. It seems that Namecheap is responding to that request, not your Go program... look at the response headers.

**Comment by lyihongl** [comment]
How come when I added the print statement into the certmagic.go code though, it prints the ip of my droplet?

**Comment by mholt** [comment]
No clue, but it's definitely not CertMagic answering your request. Let me know what you find out!

**Comment by lyihongl** [comment]
Hey, I figured it out. The other IP was namecheaps URL forwarding server. The way I had it setup, my url redirect and A record were conflicting, which was causing the problem. Now everything works properly.

**Comment by mholt** [comment]
Okay, excellent! Thanks for following-up. That will help others who experience the same problem. :)
