### ISSUE TITLE
Use a custom CSR

### ISSUE THREAD

**Issue by kompiuter** [mholt/certmagic#50]
## What is your question?
I'm attempting to create a certificate using LetsEncrypt and DNS01 challenge with DNSimple. I would like to provide my own Certificate Signing Request (CSR) rather than having the library create its own. How can I do this?

## What have you already tried?
I've looked at the codebase and I believe this is something that is delegated to the go-acme library, but I don't see any clear way of configuring it.

**Comment by mholt** [comment]
We can probably add this... but first, why do you want to create your own CSR?

**Comment by mholt** [comment]
To do this with the latest commit, you can implement an `Issuer` of your own. If all you want to do is use your own CSR, you can embed the `ACMEManager` (the default `Issuer` type) into your type, take the input CSR and craft your own CSR from it, then wrap the embedded `Issue()` method. Tada.

And if you need your own key as well, just implement and set `Config.KeySource`.
