### ISSUE TITLE
Can HTTPS be exposed directly to the internet?

### ISSUE THREAD

**Issue by andy9775** [mholt/certmagic#9]
## What would you like to have changed?
More of a feature request/question. 

I'm curious if calling `certmagic.HTTPS` without a proxy in front of it is safe. Cloudflare has a (dated) post [here](https://blog.cloudflare.com/exposing-go-on-the-internet/) on config details for exposing a go server to the public internet. 

My services have always sat behind a proxy of sorts and I'm interested in just exposing to the internet. 

I know caddy uses this library, but does it use custom configurations?

## Why is this feature a useful, necessary, and/or important addition to this project?
It would allow a go service to be exposed to the internet without a proxy in front of it.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
My services (go or other) sit behind nginx

**Comment by mholt** [comment]
Right now it uses defaults that the Go standard library uses. It's a high-level convenience function to replace http.ListenAndServe. You can, of course, still create your own listeners and servers with the timeouts and TLS settings you prefer.

If we did set default timeouts, what should they be? We'd have to pick values that work for, well, everyone. (As for a custom TLS config, can definitely do that, as I'm already doing that with Caddy.)

**Comment by andy9775** [comment]
> We'd have to pick values that work for, well, everyone.
Agree. Wanted to ensure that there wasn't a best practices config already that I was missing.

Thanks!

**Comment by mholt** [comment]
@andy9775 I went ahead and added some default timeouts in 52238b4 -- let's see if anyone complains. `certmagic.HTTPS()` should now be production-ready for most users.

**Comment by andy9775** [comment]
@mholt awesome, thanks. And thanks for the great package.
